return {
    {name = "autumn", config = {'Xmult'}},
    -- {name = "enterthetribe", config = { 'odds' }},
    -- {name = "devourer", config = { 'odds', 'odd_base', 'x_Xmult', 'Xmult' }},
    -- {name = "roses", config = { 'mult', 'punish', 'x_mult' }},
    -- {name = "tulips", config = { 'mult', 'punish', 'x_mult' }},
    -- {name = "sunflowers", config = { 'mult', 'punish', 'x_mult' }},
    -- {name = "lilac", config = { 'mult', 'punish', 'x_mult' }},
    -- {name = "spring", config = { 'chips', 'x_chips' }},
    -- {name = "gcu", config = { 'chips', 'x_chips' }},
    -- {name = "summer", config = { 'mult', 'punish', 'x_mult' }},
    {name = "prime", config = {'mult'}},
    {name = "player", config = {'chips', 'x_chips'}},
    -- {name = "proudjoker", config = {}},
    -- {name = "texts", config = { 'chips' }},
    -- {name = "umbrella", config = { 'chips' }},
    -- {name = "winter", config = {}},
    -- {name = "ai", config = {}},
    {name = "patch", config = {'trigger', 'rounds'}},
    {name = "mis_scaled", config = {}},
    -- {name = "magnifyingglass", config = {}},
    -- {name = "thecow", config = {}},
}